version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_node_sequelize_test
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  api:
    build: ./
    container_name: node_sequelize_test
    ports:
      - "4000:4000"
    volumes:
      - ./node_modules
volumes:
  db:
    driver: local
