version: "3.8"
services:
  db-seq:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_node_sequelize_test
    ports:
      - "5432:5432"
    volumes:
      - db-seq:/var/lib/postgresql/data
  api:
    build: .
    container_name: node_sequelize_test
    ports:
      - "4000:4000"
    # command: npm run dev
    volumes:
      # - ./app
      # - ./app/node_modules
      - ./:/usr/src/app
      - /usr/src/app/node_modules
volumes:
  db-seq:
    {}
    # driver: local
